# Generated by Django 4.2.2 on 2023-06-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=50, verbose_name='название автомобиля')),
                ('car_year', models.CharField(max_length=50, verbose_name='год выпуска')),
                ('car_mileage', models.CharField(max_length=50, verbose_name='пробег автомобиля')),
                ('car_description', models.TextField(verbose_name='описание автомобиля')),
                ('car_contact', models.CharField(max_length=50, verbose_name='контактные данные владельца')),
            ],
        ),
    ]
