# Generated by Django 3.2 on 2023-06-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'автомобиль', 'verbose_name_plural': 'автомобили'},
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_contact',
            new_name='car_price',
        ),
    ]
